Flt 1317 validate package
surfstudio/flutter-render-metrics pull request #1
Opened 2021-09-22 12:19 UTC by roketstorm

Поправил ошибки анализатора. Немного изменил генерацию тестового виджета, как требовал анализатор.

2021-09-23 08:12 UTC, dkrutskikh requested changes

2021-09-23 08:12 UTC, dkrutskikh commented on lib/src/render/render_metrics.dart
> +  // ignore: member-ordering-extended
@roketstorm зачем это?

2021-09-23 09:13 UTC, roketstorm commented on lib/src/render/render_metrics.dart
> +  // ignore: member-ordering-extended
Если я правильно понял, в анализаторе возникла коллизия, что свойства, описанные в геттере не описаны выше конструктора. То есть, анализатор так понял, что свойства должны принадлежать _RenderMetricsBox_, а не возвращаемому объекту _RenderData_.
Поэтому поставил комментарий для игнора анализатором.

2021-10-04 09:59 UTC, MbIXjkee commented on test/test_utils.dart
> +class TestableWidget extends StatelessWidget {
доку

2021-10-04 09:59 UTC, MbIXjkee commented on lib/src/render/render_metrics.dart
> +  // ignore: member-ordering-extended
скорее он предлагает публичный геттер тоже поднять выше конструктора

2021-12-13 10:14 UTC, closed without merging